# Generated by Django 4.1 on 2022-09-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.IntegerField(max_length=15)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.address')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.IntegerField(max_length=15, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.address')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.university')),
            ],
        ),
    ]
