# Generated by Django 4.1 on 2022-09-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_remove_faculty_mobile_number_faculty_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='phone_number',
        ),
    ]
