# Generated by Django 4.1 on 2022-10-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_remove_faculty_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
