# Generated by Django 4.1 on 2022-10-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_faculty_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='address',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
