# Generated by Django 4.1 on 2022-10-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='Title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
