# Generated by Django 4.1 on 2022-10-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_coursecontent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='youtubelink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
