# Generated by Django 4.1 on 2022-11-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_coursecontent_youtubelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_layout',
            field=models.TextField(blank=True, null=True),
        ),
    ]
