# Generated by Django 4.0.6 on 2022-11-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_enrollment_course_alter_enrollment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
