# Generated by Django 4.0.6 on 2022-11-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0012_enrollment_certificate_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_generated',
            field=models.BooleanField(default=False),
        ),
    ]
